SBfinder/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import os
from . import views

app_name = 'SBfinder'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('classes/', views.getClasses, name='class'),
    path('createuser/', views.create_user, name = 'create_user'),
    path('<slug:slug>/userprofile/', views.UserProfileView.as_view(), name = 'profile'),
    path('addtoschedule/', views.add_to_schedule, name='add_to_schedule'),
    path('deletefromschedule/<int:id>', views.delete_from_schedule, name='delete_from_schedule'),
    path('studyBuddyList/', views.generate_SB, name = 'generate_SB'),
    path('send_friend_request/<str:userID>/', views.send_friend_request, name = "SFR"),
    path('accept_friend_request/<int:requestID>/', views.accept_friend_request, name = "AFR"),
    path('delete_friend/<int:id>', views.delete_friend, name='delete_friend'),
    path('friendrequest/', views.friendView.as_view(), name = 'friend_request'),
    path('accept_SS_request/<int:requestID>/', views.accept_SS_request, name='ASR'),
    path('studysession/', views.studyView.as_view(), name = 'study_session'),
    path('generateSS/', views.generateSSView.as_view(), name = 'generate_SS'),
    path('createSS/', views.create_SS, name = 'create_SS'),
    path('leaveSS/<int:id>', views.leave_study_session, name='leave_study_session'),
    path('message/<int:id>', views.message_log, name = 'message_log'),
    path('generate_message/<int:id>', views.generate_message, name = 'generate_message'),
    path('setting/<int:id>', views.settingView.as_view(), name='setting'),
    path('upload_pic/', views.upload_pic, name='upload_pic'),
    path('update_profile/', views.update_profile, name='update_profile'),


]

mysite/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

#https://project-b-10-study-buddy-finde.herokuapp.com/accounts/profile/
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name = "index.html"), name = 'index'),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
    path('sbfinder/', include('SBfinder.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SBfinder/models.py
from django.db import models
from datetime import datetime
from django.conf import settings #Foreign Key?
from django_resized import ResizedImageField
# Create your models here.


class SubjData(models.Model):
    subject = models.CharField(max_length=4) #Added to store all possible subjects in the database
    def __str__(self):
        return self.subject

class UserInfo(models.Model):
    user_name = models.CharField(max_length = 255)
    user_email = models.EmailField(max_length = 255)
    correspond_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    slug = models.SlugField(null=True, max_length = 255)
    friends = models.ManyToManyField("self", blank = True)
    avatar = models.ImageField(default = "default.jpg", blank=True, null=True)
    year = models.CharField(max_length = 255, blank = True)
    major = models.CharField(max_length = 255, blank = True)


    def __str__(self):
        return self.user_name


class Friend_Request(models.Model):
    from_user = models.ForeignKey(UserInfo, related_name = 'from_user', on_delete= models.CASCADE)
    to_user = models.ForeignKey(UserInfo, related_name='to_user', on_delete=models.CASCADE)

    def __str__(self):
        return "From" + self.from_user.user_name + " to " + self.to_user.user_name


class Course(models.Model):
    instructor = models.CharField(max_length=255, blank = True, null = True)
    course_number = models.CharField(max_length=255, blank = True, null = True)
    subject = models.CharField(max_length=255, blank = True, null = True)
    catalog_number = models.CharField(max_length=255, blank = True, null = True)
    description = models.CharField(max_length=255, blank = True, null = True)
    course_section = models.CharField(max_length=255, blank = True, null = True)
    meetings = models.CharField(max_length=255, blank = True, null = True)
    component = models.CharField(max_length=255, blank = True, null = True)
    users = models.ManyToManyField(UserInfo)

    def __str__(self):
        representation_list = str(list(self.users.all())) + "|" + str(self.subject) + " " + str(self.catalog_number) + " " +str(self.description) + "|" + str([user.pk for user in self.users.all()])

        return representation_list

class Study_Session(models.Model):
    title = models.CharField(max_length=255, blank = True, null = True)
    description = models.CharField(max_length=255, blank = True, null = True)
    time = models.TimeField()
    date = models.DateTimeField('date proposed')
    exact_time = models.DateTimeField('Exact time proposed') # exact time of the proposal by combing the previous two together
    users = models.ManyToManyField(UserInfo)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['exact_time']

class Study_Session_Request(models.Model):
    study_session = models.ForeignKey(Study_Session, on_delete= models.CASCADE)
    to_user = models.ForeignKey(UserInfo, related_name='to_user_ss', on_delete=models.CASCADE)

class Message(models.Model):
    time = models.DateTimeField('time sent')
    from_user = models.ForeignKey(UserInfo, related_name='from_user_message', on_delete=models.CASCADE)
    to_user = models.ForeignKey(UserInfo, related_name='to_user_message', on_delete=models.CASCADE)
    message_body = models.CharField(max_length=1000, blank = True, null = True)

    class Meta:
        ordering = ['time']

SBfinder/forms.py
from django.forms import ModelForm
from .models import *


class CreateInForum(ModelForm):
    class Meta:
        model = Forum
        fields = ['topic', 'description']


class CreateInDiscussion(ModelForm):
    class Meta:
        model = Discussion
        fields = ['discuss']

SBfinder/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.views import generic
from django.utils import timezone
from datetime import datetime
from django.contrib import messages

from .models import SubjData, Course
from django.contrib import admin
from .models import UserInfo, Friend_Request, Study_Session, Study_Session_Request, Message
import json
import requests
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from datetime import datetime


class IndexView(generic.ListView):
    template_name = 'SBfinder/index.html'

    def get_queryset(self):
        """Return the last five published questions."""
        return 0;


def getClasses(request):
    # model = Course // I don't think this is needed here
    data = None
    classes = []

    if 'subjSearch' in request.GET and len(request.GET['subjSearch']) > 0:  # Check if the inputed search is a valid class subject
        subj = request.GET['subjSearch'].upper()
        url = "http://luthers-list.herokuapp.com/api/dept/" + subj + "?format=json"  # If subj is valid create the api link
        response = requests.get(url)  # for the cooresponding department
        data = response.json() # if there is nothing is subSearch, data variable will remain None


    if 'numSearch' in request.GET:# Check if the inputed search is a valid class number
        if len(request.GET['numSearch']) > 0 and len(request.GET['subjSearch']) == 0:
            messages.error(request, 'Please enter a valid department number for us to search!')
            return HttpResponseRedirect(reverse('SBfinder:class'))
        else:
            catNumb = request.GET['numSearch']
            if catNumb != "":
                for i in data:
                    num = i['catalog_number']
                    if num == catNumb:
                        classes.append(i)
            else:
                if data is not None:
                    for i in data:
                        classes.append(i)
                else: # if data is None, it means the user didn't input anything to the subjSearch, but the user is still able to get here,
                     # which means the user also did not input anything to the numSearch (otherwise ln46 will handle it). Note that we can
                     # therotically also handle this exception at ln47 by adding a elif statement to redirect to the double-no-entry scenerio.
                    messages.error(request, 'Please input something for us to search!')
                    return HttpResponseRedirect(reverse('SBfinder:class'))



    return render(request, 'SBfinder/class.html',
                      {"test": classes})  # Update their website with the subjects classes, changed url to class from /index



def create_user(request):
    # get the user only based on their user model and email and nothing else
    obj, created = UserInfo.objects.get_or_create(
        user_email=request.user.email,
        correspond_user=request.user,
    )

    # if this is a newly created user, we add slug and user name based on their userModel's user name,
    # but do not modify if this is not a newly created user model
    if created:
        obj.user_name = request.user.username
        obj.slug = request.user.username
        obj.save()

    return HttpResponseRedirect(reverse('SBfinder:class'))


def add_to_schedule(request):
    # load the context variable via POST; replace single quotation with double quotation
    class_added = json.loads(request.POST['class'].replace("\'", "\""))

    obj, created = Course.objects.get_or_create(
        instructor=class_added['instructor'],
        subject=class_added['subject'],
        course_number=class_added['course_number'],
        catalog_number=class_added['catalog_number'],
        description=class_added['description'],
        course_section=class_added['course_section'],
        meetings=class_added['meetings'],
        component=class_added['component'],

    )

    current_userInfo = UserInfo.objects.get(correspond_user=request.user)

    if obj in current_userInfo.course_set.all():
        messages.error(request, 'The class is alrady in your schedule!')
        return HttpResponseRedirect(reverse('SBfinder:class'))

    obj.users.add(current_userInfo)

    messages.success(request, 'The class has been successfully added!')
    return HttpResponseRedirect(reverse('SBfinder:class'))


def delete_from_schedule(request, id):
    c = Course.objects.get(id=id)
    current_userInfo = UserInfo.objects.get(correspond_user=request.user)
    c.users.remove(current_userInfo)
    messages.success(request, 'The class has been successfully deleted!')
    return HttpResponseRedirect(reverse('SBfinder:profile', args=(current_userInfo.slug,)))


def generate_SB(request):
    result_nameDic = {}

    SB_class_list = request.POST.getlist('checks')  # get all classes that have been checked

    # Get the current user to make sure we are not adding the current user to our SB list
    current_userInfo = UserInfo.objects.get(correspond_user=request.user)

    for SB in SB_class_list:
        Splitted = SB.split("|")
        idList = Splitted[2]
        idList = idList.replace("[", "")
        idList = idList.replace("]", "")
        idList = idList.split(",")
        for i in range(len(Splitted[0].split(","))):
            name = Splitted[0].split(",")[i]
            name = name.replace("[", "")
            name = name.replace("]", "")
            name = name.replace("<UserInfo: ", "")
            name = name.replace(">", "")

            # don't want to fetch a user you already fetched
            if str(name) + ","+idList[i] not in result_nameDic.keys():
                # prevents you from getting current user as a friend
                if str(name) != current_userInfo.user_name and int(idList[i]) != current_userInfo.pk:
                    result_nameDic[str(name) + "," +idList[i]] = []

            # get all the classes
            if str(name) != current_userInfo.user_name and int(idList[i]) != current_userInfo.pk:
                result_nameDic[str(name) + "," + idList[i]].append(Splitted[1])

    return render(request, 'SBfinder/SB_list.html', {"SB_Dic": result_nameDic})


# Send Friend Request
@login_required
def send_friend_request(request, userID):
    userID = int(userID)
    from_user = UserInfo.objects.get(correspond_user=request.user)
    to_user = UserInfo.objects.get(pk=userID)
    friend_request, created = Friend_Request.objects.get_or_create(from_user=from_user, to_user=to_user)

    # Ideally redirect users to a fancier page
    if created:
        messages.success(request, 'The friend request has been sent! Please wait for the other user to respond...')
        return HttpResponseRedirect(reverse('SBfinder:friend_request'))
    else:
        messages.error(request, 'The friend request was already sent!')
        return HttpResponseRedirect(reverse('SBfinder:friend_request'))


# Accept Friend Request
@login_required
def accept_friend_request(request, requestID):
    friend_request = Friend_Request.objects.get(pk=requestID)
    if friend_request.to_user == UserInfo.objects.get(correspond_user=request.user):
        friend_request.to_user.friends.add(friend_request.from_user)
        friend_request.from_user.friends.add(friend_request.to_user)
        friend_request.delete()

        # if the other user has sent a request to you as well, delete that request too
        from_me_to_others = Friend_Request.objects.filter(from_user = friend_request.to_user, to_user = friend_request.from_user).first()
        if from_me_to_others is not None:
            from_me_to_others.delete()

        messages.success(request, 'Friend request accepted.')
        return HttpResponseRedirect(reverse('SBfinder:friend_request'))

    else:
        messages.error(request, 'Friend request not accepted.')
        return HttpResponseRedirect(reverse('SBfinder:friend_request'))

def delete_friend(request, id):
    to_user = UserInfo.objects.get(id=id)
    current_userInfo = UserInfo.objects.get(correspond_user=request.user)
    to_user.friends.remove(current_userInfo)
    current_userInfo.friends.remove(to_user)

    for message in Message.objects.all():
        if (message.to_user == current_userInfo and message.from_user == to_user) or (message.from_user == current_userInfo and message.to_user == to_user):
            message.delete()

    messages.success(request, str(to_user.user_name) + ' has been removed from your friend list!')
    return HttpResponseRedirect(reverse('SBfinder:profile', args=(current_userInfo.slug,)) + '#friend')

# create the Study session object
@login_required()
def create_SS(request):
    # if the created ss has a date and time earlier than the current date and time, delete it
    # and return an error message

    if datetime.strptime(request.POST['study_session_date'] + " " + request.POST['study_session_time'],
                         '%Y-%m-%d %H:%M') <= datetime.now():
        messages.error(request, "Oops! A time in the past won't work!")
        return HttpResponseRedirect(reverse('SBfinder:generate_SS'))

    # proceed to create if not
    study_session, created = Study_Session.objects.get_or_create(
        title=request.POST['study_session_title'],
        description=request.POST['study_session_description'],
        date=request.POST['study_session_date'],
        time=request.POST['study_session_time'],
        exact_time=request.POST['study_session_date'] + " " + request.POST['study_session_time']
    )

    # add the current user  (the user who proposed this study session) to study_session.users
    current_userInfo = UserInfo.objects.get(correspond_user=request.user)

SBfinder/templates/SBfinder/addInDiscussion.html
<head>
    <style>
        form{
            border:4px solid black;
            margin: 0 auto;
            padding: 40px;
            width: fit-content;
        }
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"0>

</head>
<form action="{% url 'SBfinder:add_in_discussion' course_id forum_id%}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-success" value="submit">
</form>

SBfinder/templates/SBfinder/addInForum.html
<head>
    <style>
        form{
            border:4px solid black;
            margin: 0 auto;
            padding: 40px;
            width: fit-content;
        }
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"0>

</head>
<form action="{% url 'SBfinder:add_in_forum' course_id%}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-success" value="submit">
</form>

SBfinder/templates/SBfinder/base.html
<!DOCTYPE html>

{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}


<html>

  <style>
    .navbar { 
    background-color: #026670;
    color: #edeae5;
    }
    
    .nav-link {
    color: #edeae5;
    }

    .navbar-brand {
    color: #edeae5;
    }

    body {
    background-color: #edeae5;
    font-family: "trebuchet ms", "sans-serif";
    min-height: 400px;
    margin-bottom: 2%;
    }

    .nav-link:hover {
    color: #17252a;
    }

    .navbar-brand:hover {
    color: #17252a;
    }

    .footer {
      position: fixed;
      left: 0;
      bottom: 0;
      width: 100%;
      height: 4%;
      background-color: #026670;
      color: #edeae5;
      text-align: center;
      font-size: .80em;
      padding: .12% 0;
    }

    
    </style>

    <nav class="navbar sticky-top navbar-expand-lg">
        <div class="container-fluid">
          <a class="navbar-brand text-capitalize" href="{% url 'SBfinder:profile' user.username %}"> Dashboard |</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/sbfinder/classes">Class Search</a>
              </li>
                <li class = "nav-item">
                  <a class="nav-link" href="{% url 'SBfinder:study_session' %}">Study Sessions</a>
                </li>
              <li class="nav-item">
                <a class = "nav-link" href = "{% url 'SBfinder:friend_request' %}"> Friend Requests </a>
              </li>
            </ul>
            <ul class="navbar-nav ms-auto">
               <li class="nav-item">
                <a class="nav-link" href="{% url 'SBfinder:setting' user.id %}">Settings</a>
               </li>
              <li class="nav-item">
                <a class="nav-link" href="/logout">Log Out</a>
              </li>
            </ul>

          </div>
        </div>
      </nav>



    <body class="d-flex flex-column min-vh-100">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </body>

    
    <!-- Footer padding top and bottom .5-->
    <div class="footer">
        <div class="m-0">Copyright &copy; Team B-10 | Yuanzhan, Dalia, Sarah, Ethan, Essam</div>
    </footer>

</html>

SBfinder/templates/SBfinder/class.html
{% extends "SBfinder/base.html" %}
{% block content %}

<style>
.button {
  background-color: #026670;
  color: #edeae5;
  border: none;
  height: 28px;
}

.btn {
  background-color: #95edd7;
  color: #026670;
}

.card-header {
  background-color: #026670;
  color: #edeae5;
}

.card-body {
  background-color: #feffff;
}

h1{
  font-size: 3.5em;
}

.right{
    float:right;
}

.left{
    float:left;
    padding: .4% 0;
}


</style>
<body>

{% include 'SBfinder/messages.html' %}

<div class="container"><br>
    <h1 class="text-center">Class Search </h1>
    <hr/>
    <form class="text-center mt-4" method="GET">
        <input type="text" name="subjSearch" placeholder="APMA, CS, etc ..." class="text-center">
        <input type="text" name="numSearch" placeholder="1010, 3240, etc ..." class="text-center">
        <button class="button" type="submit">SEARCH CLASS</button>
    </form>
</div>
<div class="mx-auto" style="width: 1200px;"><br>
    {% if test %}
    {% for i in test %}
    <form action="{% url 'SBfinder:add_to_schedule'%}" method="post">
        {% csrf_token %}

        <div class="card">
            <div class="h4 card-header">
                <strong class="left">{{ i.subject }} {{ i.catalog_number }}: {{ i.description }}</strong>
                <!-- I used a hidden input type to input the entire context variable through POST, and process it using json.loads() -->
                <input type="hidden" id="class" name="class" value="{{ i }}">
                <strong><input type="submit" value="Add to Schedule" class="btn right"></strong>
            </div>
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    Instructor: {{ i.instructor.name }} <br>
                    Section: {{ i.course_section }}-{{ i.component }} <br>
                    Class Number: {{ i.course_number }}</br>
                </blockquote>
            </div>
        </div>
    </form>
    {% endfor %}
</div>
{% else %}
<br><h3 class="text-center" style="color: #026670;">Oops! We haven't found any classes that match your description :(</h3>
{% endif %}
</body>
{% endblock %}

SBfinder/templates/SBfinder/index.html
<!DOCTYPE html>
{% load socialaccount %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Study Buddy finder's Index Page</title>
</head>
<body>

<h1> {{user.username}}, Welcome to the study buddy finder app! </h1>
<a href =/logout>Logout</a>

</body>
</html>

SBfinder/templates/SBfinder/userProfile.html
{% extends "SBfinder/base.html" %}
{% load SBfinder_extra %}
{% block content %}

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>

        .d-inline-flex{
            gap:10px;
            margin-bottom: 10px;
            margin-left: 2px;
        }

        .nounderline {
            text-decoration: none;
            color: #026670;
        }

        .btn {
        background-color: #95edd7;
        color: #026670;
        border: 2px solid #026670;
        height: 30%;
        }

        .btn:hover {
        background-color: #edeae5;
        color: #026670; 
        }


        .btnnobg {
        background-color: #03474d;
        color: #95edd7;
        border: 2px solid #03474d;
        height: 40%;
        text-decoration: none;
        }

        .btnnobg:hover {
        color: #ff0000;
        }

        .btn2 {
        background-color: #95edd7;
        color: #026670;
        border: 2px solid #026670;
        padding: 7px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        margin: 15px 20px;
        }

        .btn3 {
        background-color: #95edd7;
        color: #bb605e;
        border: 2px solid #026670;
        height: 20%;
        font-size: .80em;

        }

        a:hover {color: #026670;}

        .card-header {
        background-color: #026670;
        color: #edeae5;
        }

        .card-body {
        background-color: #feffff;
        }

        h1{
        font-size: 3.5em;
        }

        .right{
        float:right;
        }

        .left{
        float:left;
        padding: .5% 0;
        }

        ul {
            line-height: 10px;
        }

        .img-circle {
            border-radius: 50%;
        }

        /* Style images */
.container img {
  float: left;
  max-width: 60px;
  width: 100%;
  margin-right: 20px;
  border-radius: 50%;
  height: 60px;
}
    </style>
</head>

<body>

<script>
function toggle(source) {
  var checkboxes = document.getElementsByName('checks');
  for(var i=0, n=checkboxes.length;i<n;i++) {
    checkboxes[i].checked = source.checked;
  }
 }

function uncheckAll() {
 var checkAll = document.getElementById('checkAll');
 var checkboxes = document.getElementsByName('checks');

 var checkAll_status = 0;

 for(var i=0, n=checkboxes.length;i<n;i++) {
    if (checkboxes[i].checked == true) {
        checkAll_status++;
    }
  }

 // if all boxes are checked but the checkAll box is not checked, check it
 if ((checkAll_status == checkboxes.length) && (checkAll.checked == false)) {
    checkAll.checked = true;
 }

 // if not all boxes are checked but the checkAll box is checked, uncheck it
 if ((checkAll_status < checkboxes.length) && (checkAll.checked == true)) {
    checkAll.checked = false;

 }

}



</script>

{% include 'SBfinder/messages.html' %}

<div class = "pt-4 mb-0 text-center">
<img src="{{ userInfo.avatar.url }}" class="img-circle" alt="User Image" width = "200" height = "200">
</div>

<div class="col-md-12 inline-flex">
    <h2 class="pt-3 text-center text-capitalize font-weight-bold">Welcome, {{ userInfo.user_name }}!</h2>
</div>

<div class="text-center">
    <h5 class="text-center font-weight-bold">{{ userInfo.user_email }}</h5>
    {% if userInfo.year|length != 0 %}
    <h5> {{ userInfo.year }} Year</h5>
    {% endif %}

    {% if userInfo.major|length != 0 %}
    <h5> {{userInfo.major }}</h5>
    {% endif %}

</div>

<hr/>

<!-- Schedule Section -->
<form action="{% url 'SBfinder:generate_SB'%}" method="POST">
    {% csrf_token %}
    <h2 class="pt-2 pb-1 text-left font-weight-bold">&emsp;Schedule</h2>
    <div class = "text-center">
        {% if userInfo.course_set.all|length == 0 %}
        <h4 style="color:#026670;">You don't have anything in your schedule. Explore classes using the class search!</h4>
        {% endif %}
    </div>

    <div class="mx-auto" style="width: 1200px;">
        <!-- Check All box -->
        {% if userInfo.course_set.all|length != 0 %}
        <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" id="checkAll" onClick="toggle(this)"> **Check here if you
            want to select all classes in your schedule<br>
        </div>
        {% endif %}
        {% for class in userInfo.course_set.all %}

        <div class="card left-align">
            <div class="h4 card-header">
                <strong class="left">{{ class.subject }} {{ class.catalog_number }}: {{ class.description }}</strong>
                <button type="button" class="btn right">
                    <a href=" {% url 'SBfinder:delete_from_schedule' class.id%} " class="nounderline">Remove from
                        schedule</a>
                </button>
                <br>
            </div>
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    {% instructorParse_Name class.instructor as instructor_name %}
                    <strong>Instructor: </strong>{{ instructor_name }} <br>
                    {%instructorParse_Email class.instructor as instructor_email %}
                    <strong>Instructor Email: </strong>{{ instructor_email }} <br>
                    <strong>Section: </strong>{{ class.course_section }}-{{ class.component }} <br>
                    <strong>Class Number: </strong>{{ class.course_number }}</br>
                    <div class="form-check form-switch">
                        <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" name="checks"
                               value="{{ class }}" onclick="uncheckAll()">
                        <label class="form-check-label" for="flexSwitchCheckDefault">Check here if you would like to
                            search for study buddies from this class</label>
                    </div>
                </blockquote>
            </div>


        </div>
        {% endfor %}

        <br>

        {% if userInfo.course_set.all|length != 0 %}
        <div class="d-inline-flex">
            <input class="btn align-self-center" style="background-color:#026670; color:#edeae5; font-size:1.5em;"
                   type="submit" value="Generate Study Buddy" name="generate_SB"/>
        </div>
        {% endif %}

    </div>

</form>

<hr/>

<!-- Friend Section -->

<div class = "d-inline-flex">
    <h2 class="pt-2 text-left font-weight-bold">&ensp;&ensp;Friends </h2>
</div>
<div class = "text-center">
        {% if userInfo.friends.all|length == 0 %}
        <h4 style="color:#026670;">You don't have any friends yet :( Add a friend from your list of study buddies!</h4>
        <br>
        {% endif %}
</div>

<div class="container">
    <div class="row">
    {% for friend in userInfo.friends.all %}
    <div class="col-sm-3">
        <div class="card ml-2 mb-3" style="width: 17rem;">
            <div class = "card-header" style = "background-color: #03474d; display: inline; justify-content:space-between;">
                <img src="{{ friend.avatar.url }}" class="card-img-left float-left" height = "180">
                <h5 class = "text-capitalize mt-3 pt-1">{{ friend.user_name }} 
                    <button type="button" class="btnnobg right">
                        <a href=" {% url 'SBfinder:delete_friend' friend.id%} " class = "btnnobg fa fa-trash-o"></a>
                    </button>
                </h5> 
            </div>

            <div class="card-body text-center" style = "background-color: #026670; color:#edeae5;">
                <button class="btn" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    View Schedule </button>
                    <button type="button" class="btn text-center">
                        <a href=" {% url 'SBfinder:message_log' friend.id%} " class = "nounderline">Message</a>
                    </button>
                <div class="collapse" id="collapseExample">
                  <div class="card card-body">

                <!-- SCHEDULE -->
                {% for class in friend.course_set.all %}
                <ul class="list-group list-group-flush">
                    {% if class in userInfo.course_set.all %}
                    <li class="list-group-item text-center" style = "background-color: #95edd7;">{{ class.subject }} {{ class.catalog_number }}</li>
                    {% else %}
                    <li class="list-group-item text-center">{{ class.subject }} {{ class.catalog_number }}</li>
                    {% endif %}
                {% endfor %}
                </ul>
                <div class = "mt-2" style = "color: #026670; font-size: 0.6em;">*highlighted classes are classes you have in common</div>
                <!-- SCHEDULE END -->
                <br>
                  </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    </div>
</div>

</body>
{% endblock %}