SBfinder/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import os
from . import views

app_name = 'SBfinder'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('classes/', views.getClasses, name='class'),
    path('createuser/', views.create_user, name = 'create_user'),
    path('<slug:slug>/userprofile/', views.UserProfileView.as_view(), name = 'profile'),
    path('addtoschedule/', views.add_to_schedule, name='add_to_schedule'),
    path('deletefromschedule/<int:id>', views.delete_from_schedule, name='delete_from_schedule'),
    path('studyBuddyList/', views.generate_SB, name = 'generate_SB'),
    path('send_friend_request/<str:userID>/', views.send_friend_request, name = "SFR"),
    path('accept_friend_request/<int:requestID>/', views.accept_friend_request, name = "AFR"),
    path('delete_friend/<int:id>', views.delete_friend, name='delete_friend'),
    path('friendrequest/', views.friendView.as_view(), name = 'friend_request'),
    path('accept_SS_request/<int:requestID>/', views.accept_SS_request, name='ASR'),
    path('studysession/', views.studyView.as_view(), name = 'study_session'),
    path('generateSS/', views.generateSSView.as_view(), name = 'generate_SS'),
    path('createSS/', views.create_SS, name = 'create_SS'),
    path('leaveSS/<int:id>', views.leave_study_session, name='leave_study_session'),
    path('message/<int:id>', views.message_log, name = 'message_log'),
    path('generate_message/<int:id>', views.generate_message, name = 'generate_message'),
    path('setting/<int:id>', views.settingView.as_view(), name='setting'),
    path('upload_pic/', views.upload_pic, name='upload_pic'),
    path('update_profile/', views.update_profile, name='update_profile'),


]

mysite/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

#https://project-b-10-study-buddy-finde.herokuapp.com/accounts/profile/
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name = "index.html"), name = 'index'),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
    path('sbfinder/', include('SBfinder.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/index.html
<!DOCTYPE html>

{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% load socialaccount %}

<style>
body {
    background-color: #95edd7;
    font-family: "trebuchet ms", "sans-serif";
    }

.card {
    background-color: #026670;
    color: #edeae5;
    }
h5{

    color: #95edd7;
}
</style>
<body>
    <br><br><br><br><br><br>
    <div class = "col d-flex justify-content-center my-auto">
    <div class="card text-center m-auto mt-4" style="width: 400px;" >

        <div class="card-body">
            <br><h1>Study Buddy Finder</h1><br>
                {% if user.is_authenticated %}
                <h5>Welcome. You are logged in as</h5><h5 class="text-uppercase">{{ user.username }}</h5><br>
                    <a style = "color: #edeae5;" href = "{% url 'SBfinder:profile' user.username %}">Go to Profile</a><br>
                    <a style = "color: #edeae5;" href = '/logout'>Log Out</a>
                {% else %}
                    <h5><a style = "color: #edeae5;" href = "{% provider_login_url 'google' %}">Login With Google</a></h5>
                {% endif %}
                <br>
        </div>
    </div>
</div>
</body>


</html>